
[http]
    addr = "0.0.0.0:8080"

[db]
    [db.yangjian]
    dsn = "root:abc123456@tcp(58.87.64.219:3306)/test?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 5


[kafka]
    brokerList = ["localhost:9092"]
    topics = ["test"]
    groupID = "group-0"
    topic = "test"
    partition = 0
    isAsyncProduce = false
    isCluster = false

